# Generated by Django 4.1.5 on 2023-01-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewiew',
            new_name='Reviews',
        ),
    ]
