# Generated by Django 4.1.5 on 2023-01-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_rewiew_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
